name: Update Docker Hub Description
on:
  push:
    branches:
      - main
    paths:
      - README.md
      - .github/workflows/dockerhub-description.yml

concurrency:
  group: ${{ github.ref_name }}-dockerhub
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  dockerHubDescription:
    runs-on: ubuntu-22.04
    if: ${{ github.event.repository.fork == false }}
    steps:
      - uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Modify readme for DockerHub
        run: |
          sed -i '3,4d' README.md

      - name: Docker Hub Description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: nginx/nginx-ingress
          short-description: ${{ github.event.repository.description }}
