name: Release PR

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version to release"
        required: true
        default: "0.0.0"
      helm_version:
        description: "Helm version to release"
        required: true
        default: "0.0.0"

defaults:
  run:
    shell: bash

permissions:
  contents: read

jobs:
  release:
    permissions:
      contents: write
    runs-on: ubuntu-22.04
    steps:
      - name: Branch
        id: branch
        run: |
          version=${{ github.event.inputs.version }}
          version=${version%.*}
          echo "branch=release-$version" >> $GITHUB_OUTPUT

      - name: Checkout Repository
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2
        with:
          ref: ${{ steps.branch.outputs.branch }}
          token: ${{ secrets.NGINX_PAT }}

      - name: Replace
        run:  .github/scripts/release-version-update.sh ${{ github.event.inputs.version }} ${{ github.event.inputs.helm_version }}

      - name: Create Pull Request
        uses: peter-evans/create-pull-request@70a41aba780001da0a30141984ae2a0c95d8704e # v6.0.2
        with:
          token: ${{ secrets.NGINX_PAT }}
          commit-message: Release ${{ github.event.inputs.version }}
          title: Release ${{ github.event.inputs.version }}
          branch: docs/release-${{ github.event.inputs.version }}
          author: nginx-bot <integrations@nginx.com>
          body: |
            This automated PR updates the docs for ${{ github.event.inputs.version }} release.
